tenants: # dynamic_key: network_services
  - name: DC2
    mac_vrf_vni_base: 10000
    vrfs:
      - name: customer2
        vrf_id: 2
        svis:
          - id: 2
            enabled: true
            name: customer2
            nodes:
              - node: dc2-leaf1
                ip_address: 10.11.2.1/24
  

servers: # dynamic_key: connected_endpoints
  - name: IXIA
    adapters:
      - switch_ports: [Ethernet46]
        switches: [dc2-leaf1]
        mode: trunk
        vlans: 1-64,254