fabric_name: SITE4

design:
  type: l2ls

tenants: # dynamic_key: network_services
  - name: avd-testing
    vrfs:
      - name: guest
        vrf_id: 10
        svis:
          - id: 10
            enabled: true
            name: guest_10
            ip_virtual_router_addresses:
              - 10.204.10.1
            nodes:
              - node: wan1-site4
                ip_address: 10.204.10.2/24
              - node: wan2-site4
                ip_address: 10.204.10.3/24
      - name: data
        vrf_id: 20
        svis:
          - id: 20
            enabled: true
            name: data_20
            ip_virtual_router_addresses:
              - 10.204.20.1
            nodes:
              - node: wan1-site4
                ip_address: 10.204.20.2/24
              - node: wan2-site4
                ip_address: 10.204.20.3/24
