# Copyright (c) 2023-2024 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  arp:
    type: dict
    keys:
      persistent:
        type: dict
        keys:
          enabled:
            type: bool
            required: true
            description: Restore the ARP cache after reboot.
          refresh_delay:
            type: int
            description: Time to wait in seconds before refreshing the ARP cache after reboot (EOS default 600).
            min: 600
            max: 3600
            convert_types:
              - str
      aging:
        type: dict
        keys:
          timeout_default:
            description: Timeout in seconds.
            type: int
            min: 60
            max: 65535
      static_entries:
        type: list
        description: Static ARP entries.
        items:
          type: dict
          keys:
            ipv4_address:
              type: str
              required: true
              description: ARP entry IPv4 address.
            vrf:
              type: str
              convert_types:
                - int
              description: ARP entry VRF.
            mac_address:
              type: str
              description: ARP entry MAC address.
              required: true
              pattern: "^[0-9A-Fa-f]{4}\\.[0-9A-Fa-f]{4}\\.[0-9A-Fa-f]{4}$"
