

mgmt_interface: Management1/1
wan_router: # dynamic_key: node_type
  defaults:
    cv_pathfinder_transit_mode: region
    cv_pathfinder_region: Region1
    cv_pathfinder_site: REGION1_HUB
    loopback_ipv4_pool: 10.1.0.0/26
    vtep_loopback_ipv4_pool: 10.1.0.64/26
    uplink_ipv4_pool: 10.99.0.0/22
    uplink_type: p2p-vrfs # uplink to local switch
    uplink_interfaces: [ Ethernet1/13 ]
    uplink_switches: [ r1-hub-leaf1 ]
    bgp_as: 65000
    filter:
      always_include_vrfs_in_tenants:
        - region1-hub
    wan_ha:
      enabled: true
      ha_interfaces: [Ethernet1/15] 
      ha_ipv4_pool: 10.10.10.0/24
      ipsec: false
  node_groups:
    - group: R1_HUB_WAN
      structured_config:
        ethernet_interfaces:
          # This is raising the MTU on the HA interface specified above
          - name: Ethernet1/15
            mtu: 9100
      nodes:
        - name: r1-hub-wan1
          id: 1
          mgmt_ip: 172.28.137.226/17
          uplink_switch_interfaces: [ Ethernet1 ]
          l3_interfaces:
            - name: Ethernet1/9
              structured_config:
                mtu: 9000
              ip_address: 172.16.151.2/30
              wan_carrier: gmpls1
              wan_circuit_id: R1-HUB-GMPLS1
              peer_ip: 172.16.151.1
              static_routes:
                - prefix: 172.16.51.0/30
                - prefix: 172.16.52.0/30
                - prefix: 172.16.151.0/30
                - prefix: 172.16.201.0/30
            - name: Ethernet1/11
              structured_config:
                mtu: 9000
              ip_address: 172.16.103.2/30
              wan_carrier: rmpls3
              wan_circuit_id: R1-HUB-MPLS3
              peer_ip: 172.16.103.1
              static_routes:
                - prefix: 172.16.51.16/30
                - prefix: 172.16.52.16/30
                - prefix: 172.16.103.0/30
                - prefix: 172.16.113.0/30
                - prefix: 172.16.123.0/30
        - name: r1-hub-wan2
          id: 2
          mgmt_ip: 172.28.137.227/16
          uplink_switch_interfaces: [ Ethernet3 ]
          l3_interfaces:
            - name: Ethernet1/9
              structured_config:
                mtu: 9000
              ip_address: 172.16.152.2/30
              wan_carrier: gmpls2
              wan_circuit_id: R1-HUB-GMPLS2
              peer_ip: 172.16.152.1
              static_routes:
                - prefix: 172.16.51.4/30
                - prefix: 172.16.52.4/30
                - prefix: 172.16.152.0/30
                - prefix: 172.16.202.0/30
            - name: Ethernet1/11
              structured_config:
                mtu: 9000
              ip_address: 172.16.104.2/30
              wan_carrier: rmpls4
              wan_circuit_id: R1-HUB-MPLS4
              peer_ip: 172.16.104.1
              static_routes:
                - prefix: 172.16.51.20/30
                - prefix: 172.16.52.20/30
                - prefix: 172.16.104.0/30
                - prefix: 172.16.114.0/30
                - prefix: 172.16.124.0/30


### LEAFS ###

l3leaf: # dynamic_key: node_type
  defaults:
    platform: cEOSLab
    loopback_ipv4_pool: 10.1.0.0/26
    vtep_loopback_ipv4_pool: 10.1.0.64/26
    uplink_ipv4_pool: 10.99.0.0/22
    # mlag_interfaces: [Ethernet5, Ethernet6]
    # mlag_peer_ipv4_pool: 10.103.3.0/24
    # vtep: false
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  nodes:
    - name: r1-hub-leaf1
      id: 3
      mgmt_interface: Management1
      mgmt_ip: 172.28.135.179/17
      bgp_as: 65010

# vlan_internal_order:
#   allocation: ascending
#   range:
#   beginning: 3800
#   ending: 4000



# custom_structured_configuration_eos_cli: |
#  platform tfa personality arfa

